dataset:
  name: PDE_KS
  pair_id: 1-9  # Example: run on sub-datasets 1 to 3
model:
  name: Panda
  zero_shot: True  # Use foundation model in zero-shot mode
  weights: "GilpinLab/panda_mlm" # Pre-trained weights for the Panda model
  normalize: False  # Normalize the data
  context_length: 128  # Maximum length of the context for the foundation model - longer context makes inference more expensive but also more accurate